name: spreadsheet_table
description: A spreadsheet-like table. Scrollable in both axis. With headers that are always visible.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  spreadsheet_table:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter